# Site settings
name: Sweekrithi Shetty
title: Sweekrithi Shetty |  Engineer
description: Believe! Work! Succeed!
url: https://bchiang7.github.io/
baseurl: ''
email: shettysweekrithi03@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:shettysweekrithi03@gmail.com
  - title: twitter
    url: https://twitter.com/SweekrithiShet1
  - title: instagram
    url:https://www.instagram.com/sweekrithishetty22/
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/Sweekrithi22
  - title: linkedin
    url: www.linkedin.com/in/sweekrithi-shetty

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
